### PR TITLE
Fix map height

### LINKED ISSUE #51: initial map height wrong

### LINKED ISSUE #52: scrollto on map/grid toggle feels weird

### PR DESCRIPTION
**Pull request by mikeyrayvon**
close #51 close #52

### CODE REVIEW

**Comment by varffs** [comment]
I can't really review this as I can't work out why this fixes map height. I'm probably just out of the loop but without more description I don't know what this issue is nor why this fixes it.

File: src/js/main.js [hunk 1]
```diff
@@ -442,6 +442,9 @@ Site.Portraits = {
 
     // Bind arrange complete grid event
     _this.$grid.on('arrangeComplete',_this.handleArrangeComplete.bind(_this));
+
+    // Bind scroll to top on portrait click
+    $('.portrait a').on('click', Site.Player.scrollIn());
```
Comment (mixcas) [inline src/js/main.js]: The callback should not have `()` otherwise is not getting passed as a callback but executed at runtime.

wrong:
```
$('.portrait a').on('click', Site.Player.scrollIn());
```
right:
```
$('.portrait a').on('click', Site.Player.scrollIn);`
```

Comment (mixcas) [reply src/js/main.js]: Also Idk how, i really don't understand, but this breaks the player too
```
main.js?ver=4.8.4:302 Uncaught TypeError: Cannot read property 'loadVideoById' of undefined
    at Object.playVideo (main.js?ver=4.8.4:302)
```

commenting it in fixes or brakes the player, which is really weird

**Review by mixcas — CHANGES_REQUESTED** [review]
Comparing `master` to this branch i can't see what the difference in map height is.

Only difference I seem to notice is that error mentioned before that breaks the UX. Remember to always test your code before pushing.

I wonder about the error i'm getting on the player. Does it happen to you @mikeyrayvon ?

@mikeyrayvon could you provide information about what this is trying to fix, how to reproduce the error or bug, etc.

**Comment by mikeyrayvon** [comment]
we went over this together in person @mixcas you just took forever to review so you forgot. and i referenced issues in the description 🦅

File: src/js/main.js (hunk 1 above)
Comment (mikeyrayvon) [reply src/js/main.js]: ok i fix

**Comment by mixcas** [comment]
#51 says nothing, that's why I'm asking. I remember there was some extra space at the bottom of the map but i can't reproduce it.
